### PR TITLE
Added the ability to download audio + some refactoring

### PR DESCRIPTION
**Pull request by kennethgargan**
Added the ability to download audio

I also changed some variable names. Now since there are 2 download buttons, they have been renamed to:
btn_download_video
btn_download_audio

### CODE REVIEW

**Comment by aryanA101a** [comment]
@Kenneth-G I think there is a problem with your code.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 288, in apply_descrambler
    stream_data[key] = [
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 290, in <listcomp>
    "url": format_item["url"],
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "gui.py", line 78, in dl_audio_click
    FileSize=download_audio(url,path)
  File "/home/aryan/open source work/Youtube-Video-Downloader-main/GUI - YouTube Video Downloader - Tkinter/download_audio.py", line 6, in download_audio
    yt = YouTube(url)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 300, in apply_descrambler
    cipher_url = [
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'
```

**Comment by kennethgargan** [comment]
odd. After doing some digging it seems like its an issue with pytube.
It's fixed in this version of pytube: https://gitlab.com/obuilds/public/pytube@ob-v1
Which can be installed by typing: pip install git+https://gitlab.com/obuilds/public/pytube@ob-v1 --upgrade

Perhaps that could be added as part of the requirements?

**Comment by aryanA101a** [comment]
It is not working even after pip install ```git+https://gitlab.com/obuilds/public/pytube@ob-v1 --upgrade```
Yours is working?

**Comment by kennethgargan** [comment]
Yeah here is what I get while I try to download audio.
audio

What error does it throw when you try?

**Comment by aryanA101a** [comment]
It works well now. I suppose my laptop needed a restart.
Congratulations on being our first contributor :1st_place_medal: .
You did a great job :100:

**Comment by kennethgargan** [comment]
Thank you!

**Pull request merged**
