### PR TITLE
audio downloader  feature

### PR DESCRIPTION
**Pull request by ashvinimore**
Added Download Audio Button with code to download audio

### CODE REVIEW

**Comment by aryanA101a** [comment]
It throws an error.
Is it working fine in your system?

**Comment by ashvinimore** [comment]
Yes Sir.Working fine on my system
Screenshot from 2020-10-04 13-28-50

**Comment by aryanA101a** [comment]
Does it download audio? Have you tried that?
I ran it, when I try to download audio it throws an error.

**Comment by ashvinimore** [comment]
Yes it download an audio. Let me show you the clip. Thank you

Screenshot from 2020-10-04 16-06-49
Screenshot from 2020-10-04 16-07-52

**Comment by aryanA101a** [comment]
Yes now it works. I suppose my laptop needed a restart.
@ashvinimore You have done a great job :100: . 
But, I'll not be able to merge your PR as someone else pulled request 5 hours before you.
I am sorry :(

**Comment by ashvinimore** [comment]
Sure No problem.
Do you have other task,that I am able contribute on?
Thank You

**Pull request closed without merging**
