### PR TITLE
Progress bar for youtube video downloads

### PR DESCRIPTION
**Pull request by pbuggaveeti28**

### CODE REVIEW

**Comment by aryanA101a** [comment]
I asked to add it in the gui.

**Comment by pbuggaveeti28** [comment]
> I asked to add it in the gui.

this script in the same existing gui.py file or in the gui folder?

**Comment by aryanA101a** [comment]
Well, YouTube Video Downloader is projected as a graphical user interface in this repo. You have to add the loading bar in the front end(tkinter) and in the back end(python).
Are you comfortable with it?

**Comment by pbuggaveeti28** [comment]
Just go through the python script I've added. If it's ok I'll pull request

**Comment by aryanA101a** [comment]
Yes, that ok on cli :+1:

**Comment by pbuggaveeti28** [comment]
Thank You! Can you please megre it

**Pull request closed without merging**
